# Generated by Django 4.2.4 on 2023-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='null',
            field=models.CharField(default=1, max_length=25, verbose_name='blank'),
            preserve_default=False,
        ),
    ]
